name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install aiohttp aiofiles

      - name: Run the IPTV checker script
        run: |
          cd sources
          python iptv_smart_checker.py

      - name: Upload playlist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playlist
          path: sources/playlist.m3u
          retention-days: 90
